### ISSUE TITLE
Results Overview tab not showing uploaded sample sets

### ISSUE THREAD

**Issue by khyox** [fbreitwieser/pavian#10]
Whatever I try, I cannot see the "Results Overview" table populated except for the example data sets.

![image](https://cloud.githubusercontent.com/assets/4109713/25601265/187b0866-2eeb-11e7-88b9-5d9bab9af078.png)

In case it makes a difference, I imported the data using `centrifuge-kreport`.

PS: @fbreitwieser, many thanks for Pavian! I hope its related paper is about to be published. 👍

**Comment by fbreitwieser** [comment]
Hi @khyox , thanks for the report. I'm currently refactoring some parts and will try to fix this issue with that.

**Comment by fbreitwieser** [comment]
Hi @khyox , I just merged the development version with lots of changes - this bug should be fixed now, too

**Comment by khyox** [comment]
@fbreitwieser, thank you very much Florian!
