### ISSUE TITLE
Pavian not working with kraken2 reports

### ISSUE THREAD

**Issue by icbarron** [fbreitwieser/pavian#100]
Hi, I was trying to run my kraken2 report through Pavian to try it out, and it keeps telling me that the report format does not conform.
[kraken_report.txt](https://github.com/fbreitwieser/pavian/files/10347543/kraken_report.txt)
I'm running R 4.2.2 on a Windows 64 machine.

Thanks!

**Comment by abdeljalil-senhaji** [comment]
Hello,

Don't use the "--use-map-style" option is it will work.
