### ISSUE TITLE
Error in &&: 'length = 29' in coercion to 'logical(1)

### ISSUE THREAD

**Issue by artiman16** [fbreitwieser/pavian#106]
Hello! Advise me, why I get this error after R upgrading to 4.3.0:

Listening on http://127.0.0.1:6129
The `name` provided ('sun-o') does not correspond to a known icon
[апр28 16:17] Started new shiny session #1 ( session(s) running)
[апр28 16:20] Reading files in /tmp/Rtmpjxgb94/38dd9caaf64e7b6a1d5735bc
Предупреждение: Error in &&: 'length = 29' in coercion to 'logical(1)'
  3: runApp
  2: runUrl
  1: shiny::runGitHub
[апр28 16:20] Exiting session #1

**Comment by bheimbu** [comment]
hi @fbreitwieser,

I get the same error message. Any help is highly appreciated,

Cheers Bastian

**Comment by ktmbiome-niaid** [comment]
Hi @fbreitwieser,
I am also running into the same error message. This is occurring when trying to upload files. I have tried selecting files individually and selecting a full directory. I have also tried only uploading one file at a time, and uploading from an Rstudio Server environment or Rstudio on my desktop.

Many thanks for any thoughts you have!
--Katie

**Comment by artiman16** [comment]
Hi!
I tried push the app from docker and it was succesfull. Try!

**Comment by artiman16** [comment]
> Hi, I am also running into the same error message. This is occurring when trying to upload files. I have tried selecting files individually and selecting a full directory. I have also tried only uploading one file at a time, and uploading from an Rstudio Server environment or Rstudio on my desktop.
> 
> Edit to add: this also occurs when I ask the app to use the provided sample data. And I also noticed that the app itself hasn't been updated since 2021 (and I've used Pavian since then -- though not in my current environment), so I wonder if it's an update of R that's changed how the app works? (I'm running R-4.2.2 which isn't as up-to-date as @artiman16)
> 
> Many thanks for any thoughts you have! --Katie
