### ISSUE TITLE
how

### ISSUE THREAD

**Issue by timeresistance1996** [fbreitwieser/pavian#109]

**Comment by timeresistance1996** [comment]
How does Pavian define the pathogen. Is it based on species classification names using software such as Kraken？

**Comment by gregorysprenger** [comment]
Yes. I would recommend you read through the [pavian paper](https://doi.org/10.1093/bioinformatics/btz715).

**Comment by fbreitwieser** [comment]
Thanks for responding @gregorysprenger . What's a pathogen or not the tool cannot define, it can just show you what species are present, and those species which are more present in some (pathogenic) samples and not in others may be pathogens.
