### ISSUE TITLE
Running pavian on a remote machine and accessing sample there

### ISSUE THREAD

**Issue by riemannzetagambit** [fbreitwieser/pavian#12]
Howdy there. I run Pavian on a remote machine that is my computational workhorse and use ssh to do port forwarding to my local machine to actually view the Pavian interface. 

I want to access the kraken files I have on that remote machine and view them in Pavian, but whenever I go to 'Upload files' in the interface I can only access my local files. Is there a remedy to this? Can I tell the actual Pavian server to look only at the remote machine's file system? For the record, I tried the following when starting the Pavian server (again on the remote machine)
`pavian::runApp(port=5000, server_dir="/path/to/kraken/files/on/remote/machine/")`
but this doesn't seem to fix anything when trying the 'Upload files' button.

Thanks much in advance!

**Comment by fbreitwieser** [comment]
Hi @riemannzetagambit , you also have to define `server_access = TRUE`. Maybe this will be changed to be the default in the future.

**Comment by riemannzetagambit** [comment]
Thanks @fbreitwieser that did the trick! In the future, do you think Pavian will have an option to automatically load a set of reports at startup defined in the Pavian call? (e.g. a `preload=/prefix/to/reports` option)

**Comment by fbreitwieser** [comment]
For now, a workaround to that is to bookmark the state - link is in the sidebar. This bookmarks the locations and currently loaded data.

**Comment by fbreitwieser** [comment]
Pavian now has additionally the parameter `load_server_directory`. Set it to to true for that functionality.
