### ISSUE TITLE
Problem exporting comparison data

### ISSUE THREAD

**Issue by eugenibc** [fbreitwieser/pavian#15]
Hello,
I write you because I'm using pavia to compare the taxonomic profiles of 9 sequence libraries binned with centrifuge; I'm able to visualize the full dataset with pavian, but when I try to download the comparison table in tab format the following error message appears and nothing is saved:
ERROR: could not find function "r_summarized_report"
Best
Eugeni Belda

**Comment by claczny** [comment]
Same problem and error here.

Thx for looking into this.

Best,

Cedric

**Comment by fbreitwieser** [comment]
Should be fixed now, let me know if it does not work as expected.

**Comment by claczny** [comment]
Thx for the quick fix!
