### ISSUE TITLE
 xdg-open error when running pavian

### ISSUE THREAD

**Issue by myshu2017-03-14** [fbreitwieser/pavian#19]
Hi,
I follow the installation to run the pavian on my ubuntu 16.04 LTS... But when I run Pavian from R, type
`pavian::runApp(port=5000)` , there is an error just as below : 

![1](https://user-images.githubusercontent.com/26398036/30643165-64a311ce-9e40-11e7-9d7d-768c0ece965d.png)

Can you help me? What should I do to fix it?
Looking for your reply. Thank you very much!

Best wishes,
Myshu

**Comment by fbreitwieser** [comment]
Hi Myshu,
pavian tries to open the url http://127.0.0.1:5000 in a browser, but doesn't find a suitable one. Have a look at https://stat.ethz.ch/R-manual/R-devel/library/utils/html/browseURL.html . As a workaround, just copy the URL into any browser, Safari or Chrome for example, and it should work.
Florian

**Comment by fbreitwieser** [comment]
To disable the launching of a browser, call
```
pavian::runApp(launch.browser = FALSE)
```

**Comment by myshu2017-03-14** [comment]
@fbreitwieser Thanks for your reply. And I have a vacation the other day...Sorry for the late reply. 
And I tried `pavian::runApp(launch.browser = FALSE)` , and the result just as below:
![image](https://user-images.githubusercontent.com/26398036/31324067-26dcd992-ace1-11e7-9245-1c209099cd89.png)

And I can't open the URL`http://127.0.0.1:6964/`. What should I do next?
Best wishes,
Myshu

**Comment by myshu2017-03-14** [comment]
What's more, I connect our server using the Xshell5.
