### ISSUE TITLE
generate HTML output

### ISSUE THREAD

**Issue by ascendo** [fbreitwieser/pavian#20]
Dear Florian,

Thank you for programming this fancy software.
During the HTML report generation,  Is there any way to add Homo Sapiens to Sankey visualization?
It doesn't include Homo sapiens and Synthetic construct in Sankey visualization.
I appreciate your time.

Regards,
Won

**Comment by fbreitwieser** [comment]
Hi @ascendo , I'll look into it

**Comment by ascendo** [comment]
@fbreitwieser. Thanks!

**Comment by fbreitwieser** [comment]
Hi @ascendo , added the option.

**Comment by fbreitwieser** [comment]
If you already tried it, try again. I realized I introduced a bug with that commit that is now fixed.

**Comment by ascendo** [comment]
I will try it soon (today) and let you know.

**Comment by ascendo** [comment]
Work it as charm!
Thank you so much.
