### ISSUE TITLE
Error using 'Generate HTML Report...' with large number of samples

### ISSUE THREAD

**Issue by Krischan** [fbreitwieser/pavian#21]
Attempt to save an HTML report for a large number of samples (~300) generates this error:

`Error in generating the report: any(taxRanks %in% my_report$taxRank) is not TRUE`

The version is `Pavian R package v0.6.2`.

**Comment by fbreitwieser** [comment]
Hello Krischan, sorry for the late response. What are is the format of the reports you input?

**Comment by Krischan** [comment]
Hi Florian, thanks for getting back. The reports are in Kraken format.

**Comment by fbreitwieser** [comment]
It seems that one of the report is not in the right format. The sankey plot needs to know the ranks, and will fail if none is available. I'll make a fix such that it just gives a warning, but does not stop the whole process if that's the case.

**Comment by fbreitwieser** [comment]
Can you let me know if it works with the latest version?

**Comment by Krischan** [comment]
I got the following error:

`Error in generating the report: 'names' attribute [2] must be the same length as the vector [1]`

**Comment by fbreitwieser** [comment]
Is it possible for you to share (a minimal set of) the report files? I tried to recreate the error, but didn't manage so far.

**Comment by fbreitwieser** [comment]
Please feel free to re-open this issue if the problem persists
