### ISSUE TITLE
Maximum upload size exceeded

### ISSUE THREAD

**Issue by damientully** [fbreitwieser/pavian#23]
Hi,

When attempting to upload a bam and index file I get the message:
Maximum upload size exceeded

Is there an option to increase the upload size when running locally?

Thanks,
Damien

**Comment by fbreitwieser** [comment]
Hi Damien,
Yep, there is an easy way on the command line. The maximum upload size is defined by the option `shiny.maxRequestSize`. To increase it to 500 MB, for example, type the following before starting pavian: 
```
options(shiny.maxRequestSize=500*1024^2)
```
If your BAM file contains the unaligned reads, you can decrease the file size before uploading by getting rid of non-aligned reads using `samtools view -F4`.

**Comment by fbreitwieser** [comment]
Added comment to the README

**Comment by ropolomx** [comment]
Hi @fbreitwieser! I am trying to upload a 6 MB Kraken report into Pavian, and I run into the Maximum upload size exceeded. I did type the `options(shiny.maxRequestSize=500*1024^2)` command before `pavian::runApp()`, but unfortunately that didn't work. Do you have other suggestions? Thank you!

**Comment by Gu2uMo** [comment]
> Hi @fbreitwieser! I am trying to upload a 6 MB Kraken report into Pavian, and I run into the Maximum upload size exceeded. I did type the `options(shiny.maxRequestSize=500*1024^2)` command before `pavian::runApp()`, but unfortunately that didn't work. Do you have other suggestions? Thank you!

I just meet the same trouble and find this, maybe it is kind of late, but you can try 'pavian::runApp(port=5000,maxUploadSize=30*1024^2)' instead of 'options(shiny.maxRequestSize=500*1024^2)' in R. It works for me

**Comment by bktorrevillas** [comment]
Hello, I had difficulty getting dependencies for R to run Pavian on our local machine so we are running it in the Docker container. Can you tell me how to pass the option to increase max upload size when launching through Docker, if it is possible? Thank you!
