### ISSUE TITLE
Error: Malformed remote specification

### ISSUE THREAD

**Issue by rec3141** [fbreitwieser/pavian#24]
Hi there, trying to install pavian from github I get the following error, any ideas? thanks

```Downloading GitHub repo fbreitwieser/pavian@master
Error: Malformed remote specification 'github::fbreitwieser/shinyFileTree
	github::dreamRs/shinyWidgets'

**Comment by rec3141** [comment]
submitted pull request #25

**Comment by jnal2003** [comment]
I am having the same issue here too. Please could this be resolved asap? Many thanks.

**Comment by rec3141** [comment]
until they accept my pull request you can install from my fork:

remotes::install_github("rec3141/pavian")

**Comment by jnal2003** [comment]
got it!!! done. thanks

**Comment by fbreitwieser** [comment]
Merged, thanks @rec3141 !
