### ISSUE TITLE
Pavian crashes on the attached dataset.

### ISSUE THREAD

**Issue by samhunter** [fbreitwieser/pavian#26]
When I try to display the Sample report for the attached file on the shiny app (https://fbreitwieser.shinyapps.io/pavian/) it crashes the app. This sample has a large fraction of viral reads.

[BC04-classification_results-Kreport.tsv.zip](https://github.com/fbreitwieser/pavian/files/1828624/BC04-classification_results-Kreport.tsv.zip)

**Comment by fbreitwieser** [comment]
Hi @samhunter , can you try the local version of pavian? I tried updating it on shinyapps, but it keeps failing due to Bioconductor dependencies. Will let you know when I've an update.

**Comment by fbreitwieser** [comment]
Hi @samhunter , does the issue still persist? It should work on the local version of pavian. Please feel free to reopen.

**Comment by samhunter** [comment]
Hi @fbreitwieser. Sorry I should have posted an update. I installed a copy on a local system, and as far as I can tell, it has been performing flawlessly. Thanks!
