### ISSUE TITLE
Across-samples plot fails when names are equal

### ISSUE THREAD

**Issue by fbreitwieser** [fbreitwieser/pavian#27]
```
Warning: Error in levels<-: factor level [2] is duplicated
Stack trace (innermost first):
    105: factor
    104: data.frame [/salz/salz7-data/projects/fbreitwieser/pavian/R/sample-module.R#252]
    103: plot_it [/salz/salz7-data/projects/fbreitwieser/pavian/R/sample-module.R#252]
    102: renderPlot [/salz/salz7-data/projects/fbreitwieser/pavian/R/sample-module.R#287]
     92: <reactive:plotObj>
     81: plotObj
     80: origRenderFunc
     79: output$sample-plot1
      2: shiny::runApp
      1: pavian::runApp [/salz/salz7-data/projects/fbreitwieser/pavian/R/runApp.R#67]
```

**Comment by pvdam3** [comment]
Hi @fbreitwieser,
I experienced this message while analysing kraken2 results in the florianbw/pavian docker image. The kraken2 report files are all called differently, so they should not be having the exact same name. What can I do to solve this issue?

![Screenshot from 2019-10-28 17-10-10](https://user-images.githubusercontent.com/12155006/67695955-43ddaf80-f9a6-11e9-85c8-1d904e08c4a9.png)

cheers.
Peter
