### ISSUE TITLE
Ability to export data

### ISSUE THREAD

**Issue by deepthoughts** [fbreitwieser/pavian#3]
Hello,
Is it possible to export the data from Pavian for all data? 
For example, one can export 10 or 100 rows but I cannot find a way to export all the rows. The server gets unresponsive when trying to render all rows. 
It would be nice to have export data button which outputs all the data as CSV or TSV without trying to show it on one page. 

Thanks for making Pavian

**Comment by fbreitwieser** [comment]
Hi @deepthoughts , I think it is a good idea, especially as the interface can freeze when loading too much data. I'll work on it.

**Comment by fbreitwieser** [comment]
Hi @deepthoughts , added a button below the comparison table ! 
Cheers, Florian
