### ISSUE TITLE
Pavian Unavailable

### ISSUE THREAD

**Issue by lec49** [fbreitwieser/pavian#32]
I have been trying to access Pavian for several days through the link provided:

https://fbreitwieser.shinyapps.io/pavian/

It says 'This Application Is Currently Unavailable' I have tried multiple web browsers each day. Is there an issue with Pavian? Has it been taken down or is there an alternative way to access it?

Thanks.

![screenshot-1](https://user-images.githubusercontent.com/37143365/39566694-5e2035e6-4eb4-11e8-8d7c-58e0a97828a7.png)

**Comment by fbreitwieser** [comment]
Hi @lec49, Please consider installing pavian it locally. Unfortunately the free hours at shinyapps are always gone very quickly, but I'll restart the instance and update it.

**Comment by tayabsoomro** [comment]
Installing Pavian through R gives the following error:

```
Warning messages:
1: In i.p(...) :
  installation of package ‘/var/folders/bb/qvcmbd5n10j7cb4gsr_6l9dw0000gn/T//RtmptDCcxM/remotes17dfb36545abe/fbreitwieser-sankeyD3-fd50a74’ had non-zero exit status
2: In i.p(...) :
  installation of package ‘/var/folders/bb/qvcmbd5n10j7cb4gsr_6l9dw0000gn/T//RtmptDCcxM/remotes17dfb68b352c3/fbreitwieser-pavian-78c11da’ had non-zero exit status
```

**Comment by fbreitwieser** [comment]
@tayabsoomro , what commands did you use for installation?

**Comment by fbreitwieser** [comment]
Please reopen if you still have problems
