### ISSUE TITLE
centrifuge output won't load

### ISSUE THREAD

**Issue by tom-dyar** [fbreitwieser/pavian#33]
Hi,

I made a tsv from centrifuge (latest from github, default options) that I have attached. I try to load this in Pavian, but get this output:

Warning: Error in $<-.data.frame: replacement has 0 rows, data has 5
Stack trace (innermost first):
    82: $<-.data.frame
    81: $<- [/Users/tdyar/workspace/pavian/R/datainput-read_report.R#556]
    80: read_report [/Users/tdyar/workspace/pavian/R/datainput-read_report.R#556]
    79: FUN [/Users/tdyar/workspace/pavian/R/datainput-read_sample_data.R#73]
    78: lapply
    77: sapply
    76: read_sample_data [/Users/tdyar/workspace/pavian/R/datainput-read_sample_data.R#73]
    75: read_server_directory1 [/Users/tdyar/workspace/pavian/R/datainput-read_server_directory.R#75]
    74: read_server_directory2 [/Users/tdyar/workspace/pavian/R/datainput-module.R#229]
    73: eval [/Users/tdyar/workspace/pavian/R/datainput-module.R#223]
    72: eval
    71: withProgress
    70: read_server_directory [/Users/tdyar/workspace/pavian/R/datainput-module.R#223]
    69: observeEventHandler [/Users/tdyar/workspace/pavian/R/datainput-module.R#382]
     2: shiny::runApp
     1: runApp [#54]
[May18 11:34] Exiting session #1

Thanks!
Tom
[centr_Day11MMVpellet_S1_L004.txt](https://github.com/fbreitwieser/pavian/files/2017535/centr_Day11MMVpellet_S1_L004.txt)

**Comment by fbreitwieser** [comment]
Hi @tom-dyar , sorry for the late reply. You need to run `centrifuge-kreport` - the standard centrifuge output currently is not supported since it does not contain the taxonomic tree.
