### ISSUE TITLE
How to use pavian to draw a centrifuge-kreport file?

### ISSUE THREAD

**Issue by BurinkiWU** [fbreitwieser/pavian#34]
For the reason that the link of "https://fbreitwieser.shinyapps.io/pavian/" is always out of work, I install pavian on my R-studio. But I have no idea how to draw a picture showed on "https://fbreitwieser.shinyapps.io/pavian/" for my centrifuge-kreport file. 
Could you do me a favor?
Thx.

**Comment by fbreitwieser** [comment]
Hi @BurinkiWU , do you have problems starting the app? 

In the R console, you need to type
```
install.packages("devtools")
devtools::install_github("fbreitwieser/pavian")
pavian::runApp()
```
