### ISSUE TITLE
Kraken2 reports not opening in Pavian

### ISSUE THREAD

**Issue by harshameghadri** [fbreitwieser/pavian#38]
Hey Florian,

I tried to upload kraken2 report format to pavian. After the upload; an error says that 

### The following files did not confirm the report format. 

Is there any way around this?

**Comment by fbreitwieser** [comment]
Can you provide example files from Kraken2? Thanks!

**Comment by harshameghadri** [comment]
This is one example file.

[P3HR1_180612_K_540_IonXpressRNA_013.fastq.fasta_report.kraken2.txt](https://github.com/fbreitwieser/pavian/files/2331712/P3HR1_180612_K_540_IonXpressRNA_013.fastq.fasta_report.kraken2.txt)

**Comment by fbreitwieser** [comment]
Hi @harshameghadri , should be working now with the latest version of Pavian.

**Comment by miangoar** [comment]
Hi Florian

Thanks a lot for Pavian, it's very easy to use :)

Recently I tried to visualize my kraken reports in Pavian website but it report the same problem :(
          "The following files did not conform the report format"

I used this custom kraken DB based in the GTDB clasification of Parks et al. (2018):
Kraken DB that i use: https://github.com/hcdenbakker/GTDB_Kraken 
The original paper of GTDB: https://doi.org/10.1038/nbt.4229
Website of GTDB: https://gtdb.ecogenomic.org/tools

I use this commands in Kraken 
raken2 --db $DB --threads 20 --report kraken2nt_report --use-names --paired R1.fastq R2.fastq 2> out. I send attaching an example of my kraken reports. Also i used the website of Pavian and the R studio version but it doesn't work

[A04MIL_kraken2nt_report.txt](https://github.com/fbreitwieser/pavian/files/3506850/A04MIL_kraken2nt_report.txt)

Can you help me with this issue please ?
Cheers from Mexico :)
