### ISSUE TITLE
Error when loading KrakenUniq reports

### ISSUE THREAD

**Issue by Krischan** [fbreitwieser/pavian#39]
The (very useful) comment lines in the KrakenUniq report prevent loading.

**Comment by fbreitwieser** [comment]
Hi @Krischan , thanks for reporting this! This should be fixed in the current version.

**Comment by ZhouHui0916** [comment]
Hi fbreitwieser ,The web site https://fbreitwieser.shinyapps.io/pavian/ can not support krakenuniq --report-file .Or i missed something. The formats are as follows.

%       reads   taxReads        kmers   dup     cov     taxID   rank    taxName
76.28   5141281 5141281 3266800457      1.1     1.12e+05        0       no rank unclassified
23.72   1598943 241     2295577120      1.06    0.105   1       no rank root
23.71   1597928 564     2295577120      1.06    0.1061  131567  no rank   cellular organisms
15.73   1060337 0       2258287516      1.05    0.9016  2759    superkingdom        Eukaryota
15.73   1060337 0       2258287516      1.05    0.9016  33154   no rank       Opisthokonta
15.73   1060337 0       2258287516      1.05    0.9016  33208   kingdom         Metazoa
