### ISSUE TITLE
Alignment viewer -- upload completed, what's next?

### ISSUE THREAD

**Issue by voutcn** [fbreitwieser/pavian#4]
The docker image looks perfect now, except for the alignment viewer. I have uploaded the bam file to pavian, but nothing was displayed on the web page. Anything wrong here? The bam is sorted and indexed. I also tried to upload the bai after uploading the bam, but still got nothing in return.

![screen shot 2016-11-14 at 3 46 49 pm](https://cloud.githubusercontent.com/assets/6329785/20257016/e9be34fa-aa81-11e6-8586-93ce747840d4.png)

**Comment by fbreitwieser** [comment]
Hi @voutcn , try again, should work now! Also added some other improvements.

**Comment by voutcn** [comment]
Great! It is good in R. Waiting for the docker image.
```
$ docker pull 'florianbw/pavian'
Using default tag: latest
Pulling repository docker.io/florianbw/pavian
Tag latest not found in repository docker.io/florianbw/pavian
```
