### ISSUE TITLE
Shiny issues: increasing maxRequestSize value not working 

### ISSUE THREAD

**Issue by bastianheimburger** [fbreitwieser/pavian#40]
Dear Florian,

I cannot increase the maxRequestSize value. I tried as you suggested but it is still not working (in Pavian, I get the error message: 'Maximum upload sie exceeded'). I am a newbie to RStudio; and don't know how to set environmental variables porperly. Please could you help me?

Cheers Bastian

**Comment by MRuinels** [comment]
Hi guys,
I got the same problem. Heeeeelp ;)
Thanks a lot 
Michi

**Comment by Bpiep** [comment]
What I did was find where Pavian is installed in R with this function:
`.libPaths()`

Then, I navigated to the directory, opened the `pavian` directory, opened the `shinyapp` directory and opened the file `app.R`.
And finally, I pasted this line under the `library(shiny)` line:

`options(shiny.maxRequestSize=500*1024^2)`

I saved the file and ran Pavian in R and there were no more errors.

**Comment by fbreitwieser** [comment]
Hi, sorry for the late reply. Please do as @Bpiep says, or run `pavian::runApp(maxUploadSize="512M")`
