### ISSUE TITLE
Kraken2 reports

### ISSUE THREAD

**Issue by petrsha** [fbreitwieser/pavian#43]
Hi,
https://fbreitwieser.shinyapps.io/pavian/ doesn't open Kraken2 reports. (When running Pavian locally it works fine, but I'd like to share the results with soe who doesn't use R.)

**Comment by pomidorku** [comment]
Have you installed and logged in to Docker Desktop in you computer? Mine is working fine.

**Comment by pomidorku** [comment]
Sorry, my question was not clear earlier.
Has your colleague installed Docker Desktop in his computer? I am using pavian in R (Ubuntu) and in win10 (after installing Docker Desktop)  and they are running fine.
In my short experience using pavian, I see it can read the actual "report".txt file, but not the xxx.kraken file.
When I tried to upload the xxx.kraken file, I received a message that my file exceeds the size limit.

**Comment by fbreitwieser** [comment]
@petrsha , just updated the shinyapps.io version. @pomidorku , pavian only supports the report file, not the .kraken files.
