### ISSUE TITLE
install link is dead

### ISSUE THREAD

**Issue by ckuenne** [fbreitwieser/pavian#45]
hi, the installation link seems to be dead: https://raw.githubusercontent.com/fbreitwieser/pavian/master/inst/shinyapp/install-pavian.R. i also tried http, same result.

**Comment by fbreitwieser** [comment]
Hi @ckuenne , thanks for the info, updating the Docker README! Please use the following commands to install:

```
if (!require(remotes)) { install.packages("remotes") }
remotes::install_github("fbreitwieser/pavian")
```
