### ISSUE TITLE
*.kraken file not working?

### ISSUE THREAD

**Issue by wolfgangrumpf** [fbreitwieser/pavian#46]
Whenever I load a .kraken file I get an error saying that the report format is bad.  Are .kraken files not supported?

**Comment by rltillett** [comment]
I'm also having trouble in having Pavian recognize reports from **kraken2**. Neither my own report, nor the one shared by a commenter in issue #38 are recognized in the online version of pavian right now...
* My kraken2 report [Fla_19.report.kraken2.txt](https://github.com/fbreitwieser/pavian/files/2891250/Fla_19.report.kraken2.txt)
* The one uploaded in issue #38 [P3HR1_180612_K_540_IonXpressRNA_013.fastq.fasta_report.kraken2.txt](https://github.com/fbreitwieser/pavian/files/2891256/P3HR1_180612_K_540_IonXpressRNA_013.fastq.fasta_report.kraken2.txt)

**Comment by gringer** [comment]
These files work in the docker image florianbw/pavian:latest. I'm guessing that the shinyapps version just hasn't been updated.

**Comment by fbreitwieser** [comment]
Hi, sorry for the late reply, @wolfgangrumpf , indeed the kraken read-level files are not supported, only the report summary files. 

@rltillett and @gringer , the shinyapps.io has been updated just now!
Florian
