### ISSUE TITLE
Load example datasets fails. Metaphlan2 results import fails too. Kraken2 results works.

### ISSUE THREAD

**Issue by Shahab991** [fbreitwieser/pavian#48]
I installed Pavian (ver. 0.8.3) using:
```
install.packages("devtools")
library(devtools)
install_github("fbreitwieser/pavian")
```
However, when I try to _Load example datasets_, it shows error.
Furthermore, I am able to import and visualize Kraken2 results but, when I try to import Metaphlan2 results, it fails.
I guess the problem in both cases are the same. Because these sample examples are also processed by Metaphlan.

> The second set is sequenced stool from the Human Microbiome Project, analyzed with MetaPhlAn.

<img width="665" alt="Screen Shot 2019-03-19 at 19 59 08" src="https://user-images.githubusercontent.com/48732534/54635762-2f871b00-4a85-11e9-817f-6188b888bb97.png">

**Comment by Shahab991** [comment]
### **UPDATE!**
I hypothesized that maybe my MetaPhlAn2 installations are problematic. Using MetaPhlAn2 on Galaxy platform and sample data on [http://huttenhower.sph.harvard.edu/galaxy](url), I generated the report. But, still it's not possible to import the results using Pavian.
<img width="960" alt="Screen Shot 2019-04-08 at 15 15 03" src="https://user-images.githubusercontent.com/48732534/55727205-c8b8aa00-5a11-11e9-8aa6-22f0309eff27.png">

**Comment by Shahab991** [comment]
w

**Comment by markb729** [comment]
The problem is that "#" is a comment.char for the base function read.table. Upon parsing a line beginning with that character, read.table will omit it, thus deleting the expected Metaphlan2 header (#SampleID       Metaphlan2_Analysis).

Simply replace the comment.char = "#" shown below (line 424 in file datainput-read_report.R) with an alternative that is less likely to be used as a text header, say comment.char = "@".

    report <- tryCatch({
      utils::read.table(myfile,sep="\t",header = T,
                        quote = "",stringsAsFactors=FALSE,
                        **comment.char = "#",** nrows = nrows,
                        check.names=FALSE)
    }, error = function(x) NULL, warning = function(x) NULL)

**Comment by Shahab991** [comment]
Great! The solution worked both for Loading **Human Microbiome Project example datasets** and also my own **Metaphlan2 results**.
Thank you very much @markb729.

Just to clarify for other users having the same problem, I did this procedure:

- [Download](https://github.com/fbreitwieser/pavian) Pavian Zip-package (at this moment 0.8.3 version)
- Extract it
- Edit this file **/Downloads/pavian-master/R/datainput-read_report.R** on the Line 442, replace **“#“** with **“@“** and save the file.
- Zip it again
- Remember, all the other dependency packages need to be installed. Here, we only install Pavian package. Also, **devtools** package needs to be installed.
- In the R Studio Console, Install Pavian package locally using these commands:
`library("devtools")`
`install_local(path = "/Users/YourUsername/Downloads/pavian-master.zip")`
- Enjoy!

**Comment by fbreitwieser** [comment]
Hi @markb729 and @Shahab991 , thanks for providing a solution. I implemented a fix and will push it to Github very soon.
