### ISSUE TITLE
mmseqs2 taxonomy report not working

### ISSUE THREAD

**Issue by bhykes1** [fbreitwieser/pavian#59]
Hi 
I have an mmseqs2 generated taxonomy report that I'm trying to upload, but I keep getting the following error. The following files did not conform the report format: 

Any idea what may be wrong with this format? 
Thanks
[taxonomyResult_report.txt](https://github.com/fbreitwieser/pavian/files/3502744/taxonomyResult_report.txt)

**Comment by fbreitwieser** [comment]
@bhykes1 , sorry for the late response. Please updated MMSeqs2 to the newest version and create the report again. It should work, then. If not, please feel free to reopen the issue!
