### ISSUE TITLE
Load several centrifuge reports into one sample sets

### ISSUE THREAD

**Issue by michoug** [fbreitwieser/pavian#6]
Dear All,

I have several centrifuge reports in a folder and I can't seem to be able to import them all in a single dataset ?
I tried to create a csv file as in the example dataset (sample_data.csv) but it tells me that 

The following files did not conform the report format: 
- centrifuge_N4_F3.report
- centrifuge_N4_F4.report
- centrifuge_N4_F5.report

Any ideas.

Best
Greg

**Comment by fbreitwieser** [comment]
Hi @michoug , do you upload them at the same time by selecting all of them? Currently, the default Centrifuge report (from `centrifuge --report-file TEST.report -x IDX TEST.fa > TEST.centrifuge.csv` ) unfortunately is not supported. You have to call `centrifuge-kreport -x IDX TEST.centrifuge.csv > TEST.pavian-report` to generate a supported format.

**Comment by michoug** [comment]
Hi @fbreitwieser ,

The issue is that for some reasons in the internal browser of Rstudio I cannot select several of them at the same time.
However when using the chrome browser it seems to work
Greg

**Comment by fbreitwieser** [comment]
Hi Greg, thanks for letting me now. I'll think about the possibility to add uploaded files to the current set, instead of always creating new ones.
Florian
