### ISSUE TITLE
Allow Kraken2Uniq Reports in Pavian

### ISSUE THREAD

**Issue by jenniferlu717** [fbreitwieser/pavian#71]
https://github.com/DerrickWood/kraken2/wiki/Manual#distinct-minimizer-count-information 

![image](https://user-images.githubusercontent.com/3779419/111206130-5efe8e80-859e-11eb-957a-90e77561924b.png)

**Comment by jenniferlu717** [comment]
[Case01_kdbMAIN.k2report.txt](https://github.com/fbreitwieser/pavian/files/6143823/Case01_kdbMAIN.k2report.txt)

**Comment by fbreitwieser** [comment]
Hi @jenniferlu717 , should work now! Please feel free to test it out and report back.
