### ISSUE TITLE
kraken report file not working

### ISSUE THREAD

**Issue by Peter-Kille** [fbreitwieser/pavian#74]
Pulled software on Saturday (10/04/21) and analysis worked beautifully.  Tried to install the package on PhD student machine to-day (12/04/2021) and it gives an error with my kraken reports.  I confirmed the reports work on my version and using the trial server link on your site.  I noticed that performed some corrections on the 11th including some code associated with file validation - could you have inadvertently have introduced a code issue ??  

Many thanks for developing a great piece of software :)

**Comment by fbreitwieser** [comment]
Hi @Peter-Kille , thanks for the bug report, and the kind words :). It seems I pushed some dev too quickly. Working to resolve this issue now.

**Comment by fbreitwieser** [comment]
Hi @Peter-Kille , it should work now! Please feel free to reopen if it doesn't

**Comment by Peter-Kille** [comment]
All tested working perfectly for kraken reports
