### ISSUE TITLE
Metaphlan3 report upload fails

### ISSUE THREAD

**Issue by pieterjanvc** [fbreitwieser/pavian#75]
Hello,

Let me start by saying I love this tool!! I'm a big Shiny enthousiast myself and I can see this app has a lot of ingenuity behind it ... well done :)

I'm trying to upload MetaPhlan 3 reports into your app, but unfortunately I get an error message. I can see that the format of these files is different from the other ones through, but I see no way in MetaPhlan3 to change the output format, nor any suggestion from your documentation on converting it. 

I attached an example file that fails to upload.

Thanks again!
PJ
[metaphlan.txt](https://github.com/fbreitwieser/pavian/files/6311829/metaphlan.txt)

**Comment by fbreitwieser** [comment]
Hi @pieterjanvc , thanks a lot for the nice words :). 

I think it should work now! Let me know and feel free to reopen if there are still problems with other files.
