### ISSUE TITLE
Loading metaphlan2 results fails

### ISSUE THREAD

**Issue by maubarsom** [fbreitwieser/pavian#8]
Hi,
Does Pavian support metaphlan2 input yet? I just (Tue 31 Jan, 16:00 CET)  downloaded the Docker image and tried loading a metaphlan2 report that looks like this:

2144_A	Metaphlan2_Analysis
k__Viruses	82.75065
k__Bacteria	17.24935
k__Viruses|p__Viruses_noname	82.75065
k__Bacteria|p__Proteobacteria	16.12059
k__Bacteria|p__Actinobacteria	1.12876
... etc

and get the following error message: 

The following files did not conform the report format: 
- 2144_A_qf_metaphlan2.report.csv

What is the expected report format? In the online documentation ( https://github.com/fbreitwieser/pavian/blob/master/inst/doc/pavian-walkthrough.pdf ) there is no mention of metaphlan2 files, so I'm not sure if some preprocessing is needed.

**Comment by fbreitwieser** [comment]
Metaphlan 2 files actually should work. I'll test it with the lines you provided

**Comment by maubarsom** [comment]
Hi! I just realized what was the problem. Apparently Pavian expects the default header for metaphlan2 files, namely:

"#SampleID\tMetaphlan2_Analysis"

Considering my example had a custom sampleID it could not load it.

**Comment by fbreitwieser** [comment]
Thanks for the info. I'll change the import checks such that it just look for `Metaphlan2_Analysis` in the header.

**Comment by boulund** [comment]
Hi, I was just testing out Pavian on some MetaPhlAn2 outputs using the florianbw/pavian docker image, and encountered what I figure must be this problem (I also use custom SampleIDs). Is this issue still present in the current version of the Docker image?
